/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bob;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Gungun
 */
public class Balanceam extends javax.swing.JPanel {

    /**
     * Creates new form Balanceam
     */
    public Balanceam() {
        initComponents();
        
       ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("C:/Users/Gungun/Documents/NetBeansProjects/bob/src/bob/backgroundimage.jpeg").getImage().getScaledInstance(background.getWidth(),background.getHeight(), Image.SCALE_DEFAULT));
       background.setIcon(imageIcon1);
    }
 public Balanceam(String username,String pwd) {
        initComponents();
        Balance obj=new Balance();
       int amount=obj.balanceam(username,pwd);
      balanceshow.setText("Rs "+String.valueOf(amount));
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        balance = new javax.swing.JLabel();
        balanceshow = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(51, 0, 51));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        balance.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("Balance:");
        jDesktopPane1.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 40));

        balanceshow.setBackground(new java.awt.Color(204, 204, 204));
        balanceshow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balanceshow.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.add(balanceshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, 30));
        jDesktopPane1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 210));

        add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, 210));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel balanceshow;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
