/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bob;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gungun
 */
public class UpdatePhone extends javax.swing.JPanel {
int userid;
    /**
     * Creates new form UpdatePhone
     */
    public UpdatePhone() {
        initComponents();
        
       ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("C:/Users/Gungun/Documents/NetBeansProjects/bob/src/bob/backgroundimage.jpeg").getImage().getScaledInstance(background.getWidth(),background.getHeight(), Image.SCALE_DEFAULT));
       background.setIcon(imageIcon1);
    }
    public UpdatePhone(int userid) {
        initComponents();
        this.userid=userid;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        labelc = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        contactup = new java.awt.TextField();
        background = new javax.swing.JLabel();

        jDesktopPane1.setBackground(new java.awt.Color(51, 0, 51));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        labelc.setForeground(new java.awt.Color(255, 255, 255));
        labelc.setText("Enter your new contact details:");
        jDesktopPane1.add(labelc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 280, 30));

        update.setBackground(new java.awt.Color(0, 51, 153));
        update.setFont(new java.awt.Font("Aharoni", 2, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jDesktopPane1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 40));
        jDesktopPane1.add(contactup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, -1));
        jDesktopPane1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        // TODO add your handling code here:
        String contact=contactup.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bob","root","Nishi@123456"); 
            String qry="Update logindetails set contact_no="+contact+" where userid='"+userid+"'";
               PreparedStatement pst=con.prepareStatement(qry); 
              if( pst.executeUpdate()==1){
                  JOptionPane.showMessageDialog(this,"Your contact details updated sucessfully" );
              }
        }
        catch(Exception e){
             Errorhandle ee=new Errorhandle();
           ee.setVisible(true);   
        }
    }//GEN-LAST:event_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private java.awt.TextField contactup;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel labelc;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
