/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bob;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author Gungun
 */
public class Update extends javax.swing.JPanel {
 GridBagLayout gridBagLayout = new GridBagLayout();
 UpdatePhone cont;
 UpdatePassword pass;
 
 
    /**
     * Creates new form Update
     */
 public Update() {
        initComponents();
       
        menucontent1.setVisible(true);
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("C:/Users/Gungun/Documents/NetBeansProjects/bob/src/bob/backgroundimage.jpeg").getImage().getScaledInstance(background.getWidth(),background.getHeight(), Image.SCALE_DEFAULT));
       background.setIcon(imageIcon1);
 }
    public Update(String username) {
        initComponents();
        int userid=0;
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bob","root","Nishi@123456");
            String qry="Select userid from logindetails where username='"+username+"'";
            PreparedStatement pst=con.prepareStatement(qry); 
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                userid=rs.getInt("userid");
            }
            else{
                    Errorhandle ee=new Errorhandle();
           ee.setVisible(true);
            }
         }
         catch(Exception e){
           Errorhandle ee=new Errorhandle();
           ee.setVisible(true);
         }
        cont=new UpdatePhone(userid);
        pass=new UpdatePassword(userid);
        menucontent1.setLayout(gridBagLayout);
       GridBagConstraints gridBagConstraints=new GridBagConstraints();
        gridBagConstraints.gridx=0;
        gridBagConstraints.gridy=0;
        menucontent1.add(cont,gridBagConstraints);
        gridBagConstraints.gridx=0;
        gridBagConstraints.gridy=0;
        menucontent1.add(pass,gridBagConstraints);
        cont.setVisible(false);
        pass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        password = new javax.swing.JButton();
        menucontent1 = new javax.swing.JPanel();
        menucontent = new javax.swing.JTabbedPane();
        contact = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jDesktopPane1.setBackground(new java.awt.Color(51, 0, 51));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setBackground(new java.awt.Color(51, 51, 51));
        password.setFont(new java.awt.Font("Aharoni", 2, 12)); // NOI18N
        password.setForeground(new java.awt.Color(51, 0, 255));
        password.setText("PASSWORD");
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jDesktopPane1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 60));

        menucontent1.setBackground(new java.awt.Color(0, 51, 102));

        menucontent.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout menucontent1Layout = new javax.swing.GroupLayout(menucontent1);
        menucontent1.setLayout(menucontent1Layout);
        menucontent1Layout.setHorizontalGroup(
            menucontent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menucontent1Layout.createSequentialGroup()
                .addComponent(menucontent, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );
        menucontent1Layout.setVerticalGroup(
            menucontent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menucontent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menucontent, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(menucontent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 410, 310));

        contact.setBackground(new java.awt.Color(51, 51, 51));
        contact.setFont(new java.awt.Font("Aharoni", 2, 12)); // NOI18N
        contact.setForeground(new java.awt.Color(51, 0, 255));
        contact.setText("CONTACT DETAILS");
        contact.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jDesktopPane1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, 60));

        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        jDesktopPane1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
        cont.setVisible(false);
        pass.setVisible(true);
    }//GEN-LAST:event_passwordActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
        cont.setVisible(true);
        pass.setVisible(false);
    }//GEN-LAST:event_contactActionPerformed

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton contact;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTabbedPane menucontent;
    private javax.swing.JPanel menucontent1;
    private javax.swing.JButton password;
    // End of variables declaration//GEN-END:variables
}
