/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bob;
import transactions.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gungun
 */
public class Withdrawlam extends javax.swing.JPanel {
String usernm;
String pwd;
    /**
     * Creates new form Withdrawlam
     */
    public Withdrawlam() {
        initComponents();
        
       ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("C:/Users/Gungun/Documents/NetBeansProjects/bob/src/bob/banking.jpg").getImage().getScaledInstance(background.getWidth(),background.getHeight(), Image.SCALE_DEFAULT));
       background.setIcon(imageIcon1);
    }
     public Withdrawlam(String username,String pwd) {
         initComponents();
       usernm=username;
       this.pwd=pwd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        withdrawl = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        withdrawlam1 = new javax.swing.JTextPane();
        background = new javax.swing.JLabel();

        jDesktopPane1.setBackground(new java.awt.Color(51, 0, 51));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        withdrawl.setBackground(new java.awt.Color(0, 0, 153));
        withdrawl.setFont(new java.awt.Font("Aharoni", 2, 12)); // NOI18N
        withdrawl.setForeground(new java.awt.Color(255, 255, 255));
        withdrawl.setText("WITHDRAWL");
        withdrawl.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));
        withdrawl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawlActionPerformed(evt);
            }
        });
        jDesktopPane1.add(withdrawl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 40));

        label1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Enter amount to be Withdrawl:");
        jDesktopPane1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 60));

        jScrollPane2.setViewportView(withdrawlam1);

        jDesktopPane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 330, 30));
        jDesktopPane1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawlActionPerformed
        String am=withdrawlam1.getText();
        int amountd=Integer.parseInt(am);
        Debited ww=new Debited(usernm,amountd,pwd);
        
        JOptionPane.showMessageDialog(this,"Amount is debited sucessfully Rs."+amountd );
         this.setVisible(false);
        Menuframe m=new Menuframe(usernm,pwd);
   m.setVisible(true);
    }//GEN-LAST:event_withdrawlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JButton withdrawl;
    private javax.swing.JTextPane withdrawlam1;
    // End of variables declaration//GEN-END:variables
}
